---
development:
  cloud_name: dg5rdxy4z
  api_key: '915965733969333'
  api_secret: TdjM6vDAFsOGA2ZZ_aexHUfEW0k
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dg5rdxy4z
  api_key: '915965733969333'
  api_secret: TdjM6vDAFsOGA2ZZ_aexHUfEW0k
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dg5rdxy4z
  api_key: '915965733969333'
  api_secret: TdjM6vDAFsOGA2ZZ_aexHUfEW0k
  enhance_image_tag: true
  static_image_support: false
